spring.application.name=Group_13
spring.datasource.url=jdbc:sqlserver://localhost:51746;databaseName=BankingDB;integratedSecurity=true;encrypt=false;trustServerCertificate=true;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true